# fly.toml app configuration file generated for xivdyetools-bot on 2025-11-23T10:09:32-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'xivdyetools-bot'
primary_region = 'iad'

[build]

[deploy]
  strategy = 'immediate'

[env]
  LOG_LEVEL = 'info'
  NODE_ENV = 'production'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  
[processes]
  app = "node dist/index.js"

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
